---
- hosts: web
  vars:
    http_port: 8080
  user: root


  tasks:
  - name: install tomcat
    apt: name=tomcat7 state=present

  - name: install subversion
    apt: name=subversion state=present

  - name: ensure tomcat is running
    service: name=tomcat7 state=running

  - name: wait for tomcat to be running
    wait_for: port={{ http_port }} delay=3

  - name: checkout nexus repository
    copy: src=helloworld.war dest=/var/lib/tomcat7/webapps/ mode=0644