---
- hosts: web
  vars:
    http_port: 8080
  user: root


  tasks:
  - name: install tomcat
    apt: name=tomcat7 state=present

  - name: restart tomcat
    service: name=tomcat7 state=running

  - name: install subversion
    apt: name=subversion state=present

  - name: copy war to tomcat
    copy: src=../helloworld.war dest=/var/lib/tomcat7/webapps/ mode=0644

  - name: wait for tomcat to be running
    wait_for: port={{ http_port }} delay=3
